### ISSUE TITLE
Logo for the project needed

### ISSUE THREAD

**Issue by deepaksinghjadon** [deepaksinghjadon/re-reg-on-the-chain#2]
Any ideas for the logo? Should preferably be an SVG logo.

**Comment by vipulchandra007** [comment]
![r2 logo](https://user-images.githubusercontent.com/30883399/29363375-5cc10a82-82ad-11e7-85a1-c273a01417a2.PNG)

**Comment by deepaksinghjadon** [comment]
Looks fine. Will use this for the project

**Comment by deepaksinghjadon** [comment]
Added to the project Wiki. Closing the issue now.
